In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [5]:
print(l)

[1, 2, 3, 4]


In [8]:
array=np.array(l)

In [18]:
np.array(l)

array([1, 2, 3, 4])

In [15]:
l1=([1,2,3],[3,4,5])

In [16]:
array2=np.array(l1)

In [20]:
np.array(l1)

array([[1, 2, 3],
       [3, 4, 5]])

In [22]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
a=np.zeros((4,4))

In [31]:
a=a.astype(int)

In [32]:
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [36]:
a=np.ones(3)
a=a.astype(int)
print(a)

[1 1 1]


In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [39]:
np.random.rand(5)

array([0.52756628, 0.07408222, 0.94218311, 0.53118208, 0.44544717])

In [40]:
np.random.randn(5)

array([ 1.22808941, -1.72534516,  0.72555226, -0.06696194, -0.10572304])

In [43]:
np.random.randint(1,100)

37

In [58]:
a=np.random.randint(1,100,20)
print(a)

[88 13 42 32 64 27 35 15 35 65 76 40 88 23 88 86 16 33 91 33]


In [48]:
a.shape

(20,)

In [59]:
a.reshape(10,2)

array([[88, 13],
       [42, 32],
       [64, 27],
       [35, 15],
       [35, 65],
       [76, 40],
       [88, 23],
       [88, 86],
       [16, 33],
       [91, 33]])

In [60]:
a.max()

91

In [61]:
a.argmax()

18

In [62]:
a.min()

13

In [63]:
a.argmin()

1

Numpy Indexing and selection

In [65]:
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [66]:
a[0:6]

array([0, 1, 2, 3, 4, 5])

In [81]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
ar2[1,1]

5

In [83]:
ar2[2,2]

9

In [89]:
ar2[:2,1:]

array([[2, 3],
       [5, 6]])

In [100]:
ar2[1:3,:2]

array([[4, 5],
       [7, 8]])

In [97]:
ar2[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [104]:
ar3=np.arange(4,20)
ar3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [105]:
ar3>8

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [108]:
ar3[ar3>8]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [110]:
np.arange(100).reshape(25,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])