**PROGRAM NO : 2**

**AIM** : Matrix operations (using vectorization) and transformation using python and SVD using Python

**PROGRAM CODE**:

In [46]:
import numpy as np

In [47]:
list=[1,2,3,4]

In [48]:
np.array(list)

array([1, 2, 3, 4])

In [49]:
list2=[[5,6,7],[6,9,2],[4,1,0]]
print(np.array(list2))
print(np.arange(0,10))
print(np.arange(0,11,2))

[[5 6 7]
 [6 9 2]
 [4 1 0]]
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [50]:
print(np.zeros(3))
print(np.zeros((3,3)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [51]:
print(np.ones(3))
print(np.ones((3,3)))
print(np.eye(3))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
print(np.linspace(0,3,6))
print(np.linspace(0,10,100))

[0.  0.6 1.2 1.8 2.4 3. ]
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798 

In [53]:
print(np.random.rand(3))
print(np.random.rand(3,4))

[0.15234515 0.50232352 0.83823821]
[[0.04192374 0.82728732 0.38891065 0.73764902]
 [0.79475604 0.12035143 0.37720277 0.60935013]
 [0.46417229 0.60633732 0.99973196 0.24408305]]


In [54]:
print(np.random.randn(3))
print(np.random.randint(4,8,2))

[-0.03799443  1.10313584 -1.92235898]
[4 5]


In [55]:
l=np.arange(0,25)
print(l.reshape(5,5))
print(l.max())
print(l.min())
print(l.argmax())
print(l.argmin())
print(l.shape)
print(l.reshape(25,1))
print(l.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
24
0
24
0
(25,)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
int32


In [56]:
k=[[5,10,15],[20,25,30],[35,40,45]]
arr=np.array(k)
print(arr[1])
print(arr[1:3])
arr[1:2]=40
arr[:]=40
arr[1:3,0:2]
kk=arr>20
arr[kk]

[20 25 30]
[[20 25 30]
 [35 40 45]]


array([40, 40, 40, 40, 40, 40, 40, 40, 40])

In [57]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
p=np.ones(10)
p*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [59]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [60]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [61]:
v=np.arange(0,9)
v.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.random.rand(1)

array([0.33406929])

In [64]:
np.random.randint(1,50,25)

array([31,  2, 22, 10, 45, 40, 41,  7, 32, 10,  2, 18, 15, 39, 21, 41, 10,
       34, 18, 33, 41, 40, 27, 13, 46])

In [65]:
np.random.randn(1,50,25)

array([[[-1.27020537, -2.50816124, -1.8123106 , ..., -0.44643465,
         -1.27732788, -0.07429487],
        [-0.58050628,  0.06997152,  0.05895656, ..., -0.19897518,
          0.39748334, -0.58418633],
        [-0.09690502, -1.02527908,  0.5135745 , ..., -1.17321249,
         -0.13731161,  0.33551079],
        ...,
        [-0.06085408,  0.23718939,  0.01660841, ...,  0.68693226,
          0.18994088,  0.95411884],
        [-0.37268881,  0.72918971, -0.14822244, ..., -0.0091523 ,
          0.16134298, -0.23245148],
        [ 0.96880241, -0.16401126, -0.11239686, ..., -0.72846091,
          0.00383111,  1.20346535]]])

In [66]:
np.random.randn(5,5)

array([[ 1.91397306, -0.80778315, -1.26477433, -0.24550774, -0.25262497],
       [-0.08294887, -0.54768512, -0.50109335, -0.59469534,  2.01975351],
       [-0.53401172,  0.05154503,  0.61506534, -1.01315937,  2.29261458],
       [ 0.37342585, -1.04094139, -0.76481691,  0.4255788 ,  0.46166209],
       [ 0.26104523,  0.69180279, -0.12655302,  1.08715892, -0.92957177]])

In [67]:
ar=np.arange(1,101)
d=ar.reshape(10,10)
d/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [68]:
l=np.arange(1,26).reshape(5,5)
l.sum(axis=0)

array([55, 60, 65, 70, 75])

In [69]:
from numpy.linalg import svd

In [70]:
a=np.array([[1,-.8],[0,1],[1,0]])

In [71]:
print (a)

[[ 1.  -0.8]
 [ 0.   1. ]
 [ 1.   0. ]]


In [72]:
a.shape

(3, 2)

In [73]:
U,S,VT=svd(a,full_matrices=True)

In [74]:
a.shape

(3, 2)

In [75]:
print(U.shape,S.shape,VT.shape)

(3, 3) (2,) (2, 2)


In [76]:
U,S,VT=svd(a,full_matrices=False)

In [77]:
print(U.shape,S.shape,VT.shape)

(3, 2) (2,) (2, 2)


In [78]:
U

array([[-7.88170109e-01,  1.87057766e-16],
       [ 3.84473224e-01, -7.80868809e-01],
       [-4.80591530e-01, -6.24695048e-01]])

In [79]:
S

array([1.62480768, 1.        ])

In [80]:
VT

array([[-0.78086881,  0.62469505],
       [-0.62469505, -0.78086881]])

**MATRIX OPERATIONS**

In [81]:
a=np.arange(0,10).reshape(5,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [82]:
b=np.arange(11,21).reshape(2,5)
print(b)

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [83]:
np.dot(a,b) 

array([[ 16,  17,  18,  19,  20],
       [ 70,  75,  80,  85,  90],
       [124, 133, 142, 151, 160],
       [178, 191, 204, 217, 230],
       [232, 249, 266, 283, 300]])

In [84]:
array_1 = map(int, input().split())

22


In [85]:
array_1

**RESULT: Program is executed successfully and output is obtained**